// Mocks generated by Mockito 5.4.6 from annotations
// in u_art/test/performance_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:u_art/data/models/performance.dart' as _i2;
import 'package:u_art/data/services/kopis_service.dart' as _i3;
import 'package:u_art/data/services/uart_api_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePerformanceDetail_0 extends _i1.SmartFake
    implements _i2.PerformanceDetail {
  _FakePerformanceDetail_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [KopisService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKopisService extends _i1.Mock implements _i3.KopisService {
  MockKopisService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Performance>> getPerformances({
    required String? stdate,
    required String? eddate,
    String? shprfnmfct,
    String? signgucode,
    int? cpage = 1,
    int? rows = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPerformances, [], {
              #stdate: stdate,
              #eddate: eddate,
              #shprfnmfct: shprfnmfct,
              #signgucode: signgucode,
              #cpage: cpage,
              #rows: rows,
            }),
            returnValue: _i4.Future<List<_i2.Performance>>.value(
              <_i2.Performance>[],
            ),
          )
          as _i4.Future<List<_i2.Performance>>);

  @override
  _i4.Future<List<_i2.Performance>> getAllPerformancesByRegion({
    required String? stdate,
    required String? eddate,
    String? signgucode = '31',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllPerformancesByRegion, [], {
              #stdate: stdate,
              #eddate: eddate,
              #signgucode: signgucode,
            }),
            returnValue: _i4.Future<List<_i2.Performance>>.value(
              <_i2.Performance>[],
            ),
          )
          as _i4.Future<List<_i2.Performance>>);

  @override
  _i4.Future<_i2.PerformanceDetail> getPerformanceDetail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPerformanceDetail, [id]),
            returnValue: _i4.Future<_i2.PerformanceDetail>.value(
              _FakePerformanceDetail_0(
                this,
                Invocation.method(#getPerformanceDetail, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.PerformanceDetail>);
}

/// A class which mocks [UartApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUartApiService extends _i1.Mock implements _i5.UartApiService {
  MockUartApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i4.Future<List<_i2.Performance>> getPerformances({
    required String? stdate,
    required String? eddate,
    String? venue,
    String? genre,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPerformances, [], {
              #stdate: stdate,
              #eddate: eddate,
              #venue: venue,
              #genre: genre,
            }),
            returnValue: _i4.Future<List<_i2.Performance>>.value(
              <_i2.Performance>[],
            ),
          )
          as _i4.Future<List<_i2.Performance>>);

  @override
  _i4.Future<_i2.PerformanceDetail> getPerformanceDetail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPerformanceDetail, [id]),
            returnValue: _i4.Future<_i2.PerformanceDetail>.value(
              _FakePerformanceDetail_0(
                this,
                Invocation.method(#getPerformanceDetail, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.PerformanceDetail>);
}
